"""Crear taula books amb constraints

Revision ID: 51020b17097b
Revises: 
Create Date: 2026-02-06 13:27:24.465787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51020b17097b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'publisher_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('books', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'categories',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'maturity_rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'small_thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'preview_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.alter_column('books', 'preview_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'small_thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'maturity_rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'categories',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'publisher_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
