"""Fer camps opcionals per a dades de Google Books

Revision ID: 1073a1202d8d
Revises: 51020b17097b
Create Date: 2026-02-06 13:28:23.468821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1073a1202d8d'
down_revision: Union[str, Sequence[str], None] = '51020b17097b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'print_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'print_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
